version: "3.3"

services:
  # Rename service
  hanu_lib_be:
    build:
      context: .
      dockerfile: Dockerfile
    # Rename container_name
    container_name: hanu_lib_be_container
    # Rename image
    image: hanu_lib_be_image
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    # Rename container
    container_name: hanu_lib_db_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
    # Rename port 5434 (NOTED BELOW) to another port if 5434 is already in use in vps
    ports:
      - "5434:5432"
    volumes:
      # Rename volume
      - hanu_lib_db_volumes:/var/lib/postgresql/data

volumes:
  hanu_lib_db_volumes:
